services:
  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./infra/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "8889:8889" # Prometheus exporter metrics
    depends_on:
      - tempo
      - loki

  # Tempo (Trace Backend)
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./infra/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"      # Tempo HTTP API
      - "4317"           # OTLP gRPC receiver (cluster internal)

  # Prometheus (Metrics Backend)
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    volumes:
      - ./infra/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9099:9090"

  # Loki (Logs Backend)
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infra/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  # Grafana (Visualization UI)
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./infra/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
      - loki
      - tempo
